[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --accept-data-loss", "npm run build"]

[start]
cmd = "./start.sh"
